version: 1
validation: sovereign
default_denom: stake
accounts: 
- name: acadmin
  coins:
  - 20000token
  - 200000000stake
  mnemonic: empower convince harsh laundry praise march party sick silly giggle icon pioneer
- name: janet
  coins:
  - 10000token
  - 200000000stake
client:
  openapi:
    path: docs/static/openapi.json
faucet:
  name: acadmin
  coins:
  - 5token
  - 100000stake
validators:
- name: janet
  bonded: 100000000stake
- name: validator1
  bonded: 200000000stake
- name: validator2
  bonded: 100000000stake